//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceMarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDetail
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public int ContactNumber { get; set; }
        public string AdminId { get; set; }
        public string Password { get; set; }
    }
}
