//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceMarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public string SessionId { get; set; }
        public string SessionDescription { get; set; }
        public string Skills { get; set; }
        public System.DateTime SessionDate { get; set; }
        public System.TimeSpan SessionTime { get; set; }
    }
}
