//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceMarking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerDetail
    {
        public string TrainerId { get; set; }
        public string TrainerName { get; set; }
        public int ContactNumber { get; set; }
        public string Email { get; set; }
        public string Skills { get; set; }
    }
}
